// @ts-nocheck
import 'dotenv/config'; import express from 'express'; import path from 'path'; import {PrismaClient} from '@prisma/client'; import {Bot, InlineKeyboard, session, Context} from 'grammy';
const db=new PrismaClient(); const app=express(); app.use(express.json()); app.use(express.static(path.join(__dirname,'public')));
const token=process.env.TELEGRAM_BOT_TOKEN; const bot=token?new Bot(token):null;
type S={step:string; data:any}; const menu=()=>new InlineKeyboard().text('💰 Deposit','deposit').text('💸 Redeem','redeem').row().text('🎮 Game Account','account').text('🎁 Freeplay','freeplay').row().text('💳 Payment Methods','methods').text('🎉 Bonus','bonus').row().text('📞 Support','support');
async function user(c:Context){const f=c.from!; return db.user.upsert({where:{telegramId:String(f.id)},update:{username:f.username},create:{telegramId:String(f.id),username:f.username}})}
if(bot){bot.use(session({initial:():S=>({step:'IDLE',data:{}})})); bot.command('start',async c=>{c.session={step:'IDLE',data:{}};await c.reply('👋 Welcome to Rohi_RB_bot! Select an option:',{reply_markup:menu()})}); bot.callbackQuery('deposit',async c=>{const methods=await db.paymentMethod.findMany({where:{active:true},orderBy:{sortOrder:'asc'}});c.session={step:'DEP_METHOD',data:{}};await c.answer();await c.editMessageText('Select your payment method:',{reply_markup:new InlineKeyboard(methods.map(m=>[{text:`💳 ${m.name}`,callback_data:`dm:${m.id}`}] as any).concat([[{text:'❌ Cancel',callback_data:'cancel'}]]))})});
for(const x of ['redeem','account','freeplay'])bot.callbackQuery(x,async c=>{c.session={step:x==='redeem'?'RED_USER':x==='account'?'ACC_GAME':'FREE_USER',data:{}};await c.answer();await c.reply(x==='redeem'?'Game username enter:':x==='account'?'Select/game name enter:':'Game username enter:')});
bot.callbackQuery(/^dm:/,async c=>{const id=c.callbackQuery.data.slice(3);const m=await db.paymentMethod.findUnique({where:{id}});c.session={step:'DEP_AMOUNT',data:{methodId:id}};await c.answer();await c.reply(`💳 ${m?.name}\nAccount: ${m?.accountName}\nTag: ${m?.accountNo}\nMinimum: $${m?.minAmount}\n\nEnter amount:`)});
bot.callbackQuery('methods',async c=>{const ms=await db.paymentMethod.findMany({where:{active:true},orderBy:{sortOrder:'asc'}});await c.answer();await c.reply(ms.length?ms.map(m=>`💳 ${m.name}: ${m.accountName} / ${m.accountNo}`).join('\n'):'Payment methods are being updated.')});bot.callbackQuery('bonus',c=>c.reply('🎉 Current bonuses are announced by staff.'));bot.callbackQuery('support',c=>c.reply('📞 Please send your question here; staff will respond.'));bot.callbackQuery('cancel',async c=>{c.session={step:'IDLE',data:{}};await c.answer();await c.reply('Cancelled.',{reply_markup:menu()})});
bot.on('message:text',async c=>{const s=c.session, t=c.message.text, u=await user(c); if(s.step==='DEP_AMOUNT'){const n=Number(t);const m=await db.paymentMethod.findUnique({where:{id:s.data.methodId}});if(!Number.isFinite(n)||n<(m?.minAmount||0))return c.reply(`Enter a valid amount (minimum $${m?.minAmount||0}).`);s.data.amount=n;s.step='DEP_SCREEN';return c.reply('📸 Please send your payment screenshot.')} if(s.step==='RED_USER'||s.step==='FREE_USER'){s.data.username=t;s.step=s.step==='RED_USER'?'RED_GAME':'FREE_GAME';return c.reply('Game name enter:')} if(s.step==='RED_GAME'||s.step==='FREE_GAME'){s.data.game=t;s.step=s.step==='RED_GAME'?'RED_AMOUNT':'READY';if(s.step==='RED_AMOUNT')return c.reply('Redeem amount enter:');} if(s.step==='RED_AMOUNT'){const n=Number(t);if(!Number.isFinite(n)||n<=0)return c.reply('Enter a valid amount.');s.data.amount=n;s.step='RED_METHOD';return c.reply('Payout method and account/tag enter:')} if(s.step==='RED_METHOD'){const [method,...rest]=t.split(' ');const r=await db.redeemRequest.create({data:{requestNo:`R-${Date.now()}`,userId:u.id,gameUsername:s.data.username,gameName:s.data.game,amount:s.data.amount,payoutMethod:method,payoutAccount:rest.join(' ')}});s.step='IDLE';return c.reply(`✅ Redeem ${r.requestNo} submitted.`,{reply_markup:menu()})} if(s.step==='READY'){const r=await db.freeplayRequest.create({data:{requestNo:`F-${Date.now()}`,userId:u.id,gameUsername:s.data.username,gameName:s.data.game}});s.step='IDLE';return c.reply(`✅ Freeplay ${r.requestNo} submitted.`,{reply_markup:menu()})} if(s.step==='ACC_GAME'){s.data.game=t;s.step='ACC_USER';return c.reply('Preferred username enter:')} if(s.step==='ACC_USER'){const r=await db.gameAccountRequest.create({data:{requestNo:`A-${Date.now()}`,userId:u.id,gameName:s.data.game,preferredUsername:t}});s.step='IDLE';return c.reply(`✅ Account request ${r.requestNo} submitted.`,{reply_markup:menu()})}});
bot.on('message:photo',async c=>{if(c.session.step!=='DEP_SCREEN')return;const u=await user(c);const r=await db.depositRequest.create({data:{requestNo:`D-${Date.now()}`,userId:u.id,methodId:c.session.data.methodId,amount:c.session.data.amount,screenshot:c.message.photo.at(-1)!.file_id}});c.session={step:'IDLE',data:{}};await c.reply(`✅ Deposit ${r.requestNo} submitted.`,{reply_markup:menu()})}); bot.catch(e=>console.error(e)); bot.start().catch(console.error)}
app.get('/api/health',(_,r)=>r.json({ok:true})); app.get('/api/requests',async(_,r)=>r.json({deposits:await db.depositRequest.findMany({include:{user:true,method:true},orderBy:{createdAt:'desc'}}),redeems:await db.redeemRequest.findMany({include:{user:true},orderBy:{createdAt:'desc'}}),accounts:await db.gameAccountRequest.findMany({include:{user:true},orderBy:{createdAt:'desc'}}),freeplays:await db.freeplayRequest.findMany({include:{user:true},orderBy:{createdAt:'desc'}})})); app.listen(Number(process.env.PORT)||3000,()=>console.log('Rohi live')); 
